import { Inter } from "next/font/google";
import "./globals.scss";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <header className="layout-header">
          <h3>어떤 제목</h3>
          {/* 메뉴 리스트 */}
          <ul>
            <li>
              <Link href={"/list"}>메뉴1</Link>
            </li>
            <li>
              <Link href={"/socket"}>메뉴2</Link>
            </li>
            <li>
              <Link href={"/dashboard"}>dashboard</Link>
            </li>
            <li>
              <Link href={"/socket"}>메뉴4</Link>
            </li>
          </ul>
          {/* 좌측 아이콘 */}
          <ul>
            <li>icon1</li>
            <li>icon2</li>
            <li>icon3</li>
          </ul>
        </header>
        <section className="layout-contents">{children}</section>
        <footer className="layout-footer">
          <section>
            <p>(주)어떤 회사</p>
            <p>경기도 어쩌구 저쩌구 00번지 빌딩 88층</p>
            <p>mail : help@ggg.com</p>
          </section>
        </footer>
      </body>
    </html>
  );
}
